# Generated by Django 2.0 on 2018-01-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morningstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssfeedurl', models.CharField(max_length=5000)),
                ('rss2html', models.CharField(default='null', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='TICKER', max_length=10)),
                ('sector', models.CharField(max_length=250)),
                ('industry', models.CharField(max_length=250)),
                ('employees', models.CharField(max_length=250)),
                ('logo', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=6000)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.Profile'),
        ),
    ]
